### PR TITLE
Ignore Error Types

### PR DESCRIPTION
**Pull request by pwgraham91**
This commit adds support for ignoring error types. One can ignore error types by error type code in the command line or in the configuration file.

### CODE REVIEW

**Comment by dark** [comment]
I think @dkgi would be the best to review this code - he has more ideas about our plan to extend the configurability of pyre via options.

**Comment by dkgi** [comment]
Don't have strong opinions here except that I would like to avoid configurability-hell. @mrkmndz and @shannonzhu, thoughts?

**Comment by pwgraham91** [comment]
FYI: I updated the branch to fix a merge conflict in configuration_test.py

**Comment by dark** [comment]
Thanks, I will update the pull request internally.

Speaking of the solution and problem it's solving, I think this makes sense: some developers might want to disable some error classes for errors they do not care about.
I have not reviewed this code yet though - still waiting for feedback from the team.

**Comment by dark** [comment]
Hi @pwgraham91, sorry for the huge delay in the review.
The team could not find a consensus on whether to merge this feature, and the argument was that we are trying to maintain a consistent experience across all users of Pyre.
Unfortunately we will not be able to accept this pull request at this time, but thanks for submitting the patch!

**Pull request closed without merging**
