### PR TITLE
Sinks and type definitions for the mysql.connector

### PR DESCRIPTION
**Pull request by maximmasiutin**
Here are the sinks and the type definitions for the mysql.connector. With these files, Pyre is able to find all three SQL injection vulnerabilities in the following example:
[unsafe-mysql-py.zip](https://github.com/facebook/pyre-check/files/6338706/unsafe-mysql-py.zip)

Fixes https://github.com/facebook/pyre-check/issues/411

### CODE REVIEW

**Comment by arthaud** [comment]
That's awesome!
cc @onionymous for the .pysa
Could you make a pull request to https://github.com/python/typeshed with the mysql stubs? This way, everyone could benefit from them, not just pyre.

**Comment by onionymous** [comment]
Thank you very much for doing this! The Pysa models look good to me and are in the correct location.

+1 for the Typeshed PR - the type stubs look amazing!

**Comment by maximmasiutin** [comment]
These mysql stubs are very basic, I've trimmed them to just be useful for Pyre/Pysa, and deleted the rest. 

In order to push them to https://github.com/python/typeshed -- they need to be more or less complete.

Also, there is a message about MySQL stubs at https://github.com/python/typeshed/issues/146#issuecomment-680783332

**Comment by onionymous** [comment]
Perhaps you can consider submitting a PR to add typing to the mysql project itself (https://github.com/mysql/mysql-connector-python)? I believe it would be a smaller change than this PR, since you'd just be adding annotations for the connection and cursor objects. As with the discussion on #413, generally we'd prefer not to maintain type stubs if possible.

However, if there are further issues, we would be happy to merge this, since it's a really great contribution that improves our coverage.

**Comment by maximmasiutin** [comment]
@onionymous Thank you! Please consider merging this request, since we still need the .pysa file, even if the developers of the mysql-connector-python will add the annotations for the connection and cursor object. Then, we will be able to delete the .pyi files for MySQL from the pyre-check repository.

**Comment by maximmasiutin** [comment]
Please consider accepting this pull request. When and if the developers of the "mysql.connector" will add the stubs, we may delete the stubs that I have prepared from the repository. These stubs are mainly focused on SQL Injections for Pyre, so they are incomplete. They only define the connection and cursor types for Pyre. 

Most probably, the developers of the "mysql.connector" may need the stubs fully converted. I have submitted a https://github.com/mysql/mysql-connector-python/pull/67 , though.

**Comment by maximmasiutin** [comment]
If you accept this pull request, please also add the stubs/mysql directory to the list of directories checked by GitHub on pull request, e.g. on the validity of code formatting by "black".

**Comment by gbleaney** [comment]
@maximmasiutin thanks for putting up https://github.com/mysql/mysql-connector-python/pull/67! I think that you could actually get away with a much smaller PR. I think @onionymous was suggesting you add explicit inline return types. If you add those types in these places, I think that would be enough to give Pysa the type information it needs to catch the SQL vulnerabilities you had in #411:

https://github.com/mysql/mysql-connector-python/blob/d1e89fd3d7391084cdf35b0806cb5d2a4b413654/lib/mysql/connector/__init__.py#L188

https://github.com/mysql/mysql-connector-python/blob/86cceb2bc914362e0990459002976c7e5a271e1d/lib/mysql/connector/abstracts.py#L992

https://github.com/mysql/mysql-connector-python/blob/86cceb2bc914362e0990459002976c7e5a271e1d/lib/mysql/connector/abstracts.py#L1054

That solution is actually preferable to the `.pyi` file solution, because the presence of `.pyi` files means Pyre and Pysa are not allowed to look at the source code of the files those `.pyi` files add typeing too ([see the PEP](https://www.python.org/dev/peps/pep-0484/#stub-files)).

> Please consider accepting this pull request.

Let's wait a bit to see the result of https://github.com/mysql/mysql-connector-python/pull/67. If we can't get that landed in a reasonable time, we'll definitely land this request because it's adding some really awesome SQL sink coverage that will benefit you, us, and probably a lot of other open source users.

**Comment by maximmasiutin** [comment]
@gbleaney Thank you! I knew that @onionymous was suggesting to modify the .py files to just add types in a few places, but I don't think that the developers of mysql-connector would have allowed this. It would have broken compatibility with Python2.

**Comment by gbleaney** [comment]
@maximmasiutin there is actually a backwards compatible way to add types to Python code:
https://www.python.org/dev/peps/pep-0484/#type-comments

It's more limited that what's available in later versions of Python 3, but it's more than enough to let you specify function return types

**Comment by maximmasiutin** [comment]
> @maximmasiutin there is actually a backwards compatible way to add types to Python code:
> https://www.python.org/dev/peps/pep-0484/#type-comments

@gbleaney -- Thank you! I'm aware about comment-style type hints for Python 2, but I was not aware that Pyre supports such kind of type hints. Let us wait for the decision on https://github.com/mysql/mysql-connector-python/pull/67 -- if it will be rejected, I will try to ask to add type hint comments by a pull request.

**Comment by maximmasiutin** [comment]
Can you accept this pull request now, and when (and if) the files become available via the 'pip update mysql-connector', you will just delete the .pyi files from the pyre-check repository and only leave the .pysa file?

The developers of MySQL moved the pull request mysql/mysql-connector-python#67  to http://bugs.mysql.com/bug.php?id=103488 and closed the pull request on GitHub.

Anyway, it takes time between accepting the request and the availability of files via the 'pip install'.

**Comment by gbleaney** [comment]
@maximmasiutin I've imported your request to our internal CI so I can see if it creates any issues. At the same time, I'll check with the team to see if we're OK merging as you've proposed. I really don't want us maintaining these stubs, but the models do add some very valuable coverage.

**Comment by maximmasiutin** [comment]
@gbleaney 
Thank you! I see there are issues with the internal linter. Can you let me know the exact details, so I fix them?

**Comment by gbleaney** [comment]
@maximmasiutin the linter is complaining about two things:

1. Every file needs a copyright header:
```
# Copyright (c) Facebook, Inc. and its affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.
```
2. The [black](https://github.com/psf/black) formatter needs to be run.

**Comment by maximmasiutin** [comment]
OK, Thank you! I was using Black from pip install, but did only support .pyi and .pi file, not the .pysa files. Will check that one from https://github.com/psf/black, not from the pip install.

**Comment by maximmasiutin** [comment]
I have added the copyright headers to the .pyi files. As about the Black, the files were already formatted.

**Comment by gbleaney** [comment]
@maximmasiutin Strange, you must be on a different version of Black. Internally, it's complaining that it wants the `from typing import Any` imports at the top, above the relative imports. Anyway, I can just run the auto-fixer for these issues before I land it.

**Comment by maximmasiutin** [comment]
@gbleaney - I installed it by pip3 install git+git://github.com/psf/black 

When I run `black --version` I got `black, version 21.4b2`

I run just `black .` without any command-line parameters.

**Comment by maximmasiutin** [comment]
When I run black, it does not give any error, but when I run PyLint, I get errors.

For example:

`pylint abstracts.pyi | grep ": E"`


```
abstracts.pyi:7:0: E0402: Attempted relative import beyond top-level package (relative-beyond-top-level)
abstracts.pyi:8:0: E0402: Attempted relative import beyond top-level package (relative-beyond-top-level)
abstracts.pyi:9:0: E0402: Attempted relative import beyond top-level package (relative-beyond-top-level)
abstracts.pyi:14:0: E0402: Attempted relative import beyond top-level package (relative-beyond-top-level)
abstracts.pyi:15:0: E0402: Attempted relative import beyond top-level package (relative-beyond-top-level)
abstracts.pyi:32:26: E0602: Undefined variable 'MySQLConnectionAbstract' (undefined-variable)
abstracts.pyi:54:40: E0601: Using variable 'MySQLCursorAbstract' before assignment (used-before-assignment)
```

**Comment by maximmasiutin** [comment]
If I go to lines 32 and 54 (where the linter gives errors), I see the following:

32:
`    
def database(self) -> MySQLConnectionAbstract: ...
`

54:
`    
def info_query(self, query: Any) -> MySQLCursorAbstract: ...
`

**Comment by gbleaney** [comment]
@maximmasiutin I believe Pyre supports postponed evaluation of annotations, but if you want to make PyLint happy, you can put the `MySQLCursorAbstract` annotations in quotes. More details here:
https://stackoverflow.com/questions/33533148/how-do-i-type-hint-a-method-with-the-type-of-the-enclosing-class

As for the "Attempted relative import" errors, it looks like you've got import statements for non-existant modules. To work around that, you can remove the imports or use the `__getattr__` trick described here in the "Stub files may be incomplete." bullet:
https://www.python.org/dev/peps/pep-0484/#stub-files

**Comment by maximmasiutin** [comment]
@gbleaney - I've fixed the lint errors. Please review. By the way, I had to install the mysql-connector module via "pip install" in order to avoid the pylint errors about missing modules.

**Pull request closed without merging**
