### PR TITLE
Add more Django model fields

### PR DESCRIPTION
**Pull request by dirn**
This adds the following fields to `django.db.models.fields`

* `DecimalField`
* `FloatField`
* `SmallAutoField`
* `TimeField`
* `URLField`

### CODE REVIEW

**Comment by dirn** [comment]
This can't be merged cleanly within #256. I'll move it out of draft status once that's been merged and this has been rebased onto `master`.

**Comment by gbleaney** [comment]
@dirn do you mind rebasing and resolving the conflicts?

**Comment by dirn** [comment]
@gbleaney there weren't any conflicts when I did the rebase. Let me know if the internal tests catch anything.

**Comment by gbleaney** [comment]
Sorry for the slow responses; my attention has been a bit split. Landing now. Thanks for taking the time to send us these PRs!

**Comment by dirn** [comment]
You mean your job isn't just to wait for me to send you PRs to review and merge? 😉 

Thanks for merging them in.

**Pull request closed without merging**
