### PR TITLE
Adds pysa models for boto3 clients batch 3/inf

### PR DESCRIPTION
**Pull request by abishekvashok**
Adds pysa models for boto3 clients - athena, apprunner, and braket.

Test plan:
- run `pyre analyze --no-verify` against the following code:
```python3
import flask
import boto3
from flask import Flask, render_template
from mypy_boto3_apprunner import AppRunnerClient
from mypy_boto3_athena import AthenaClient
from mypy_boto3_braket.client import BraketClient

app = Flask(__name__)

@app.route("/vuls/<string:payload>")
def definite_vuls(payload: str) -> None:
    client1: AppRunnerClient = boto3.client('apprunner')
    response1 = client1.create_service(
        ServiceName='string',
        SourceConfiguration={
            'CodeRepository': {
                'RepositoryUrl': payload,
            }
        }
    )

    client2: AthenaClient = boto3.client('athena')
    response2 = client2.create_named_query(
        Name='string',
        Description='string',
        Database='string',
        QueryString=payload,
        ClientRequestToken='string',
        WorkGroup='string'
    )
    response3 = client2.create_prepared_statement(
        StatementName='string',
        WorkGroup='string',
        QueryStatement=payload,
        Description='string'
    )

    client3: BraketClient = boto3.client('braket')
    response4 = client3.create_quantum_task(
        action=payload,
        clientToken='string',
        deviceArn='string',
        deviceParameters='string',
        outputS3Bucket='string',
        outputS3KeyPrefix='string',
        shots=123,
        tags={
            'string': 'string'
        }
    )
```
with the pyre configuration:
```json
{
  "source_directories": [
    "."
  ],
  "taint_models_path": "../../stubs",
  "search_path": [
    ".",
    {"site-package": "boto3" },
    {"site-package": "mypy_boto3_apprunner"},
    {"site-package": "mypy_boto3_braket"},
    {"site-package": "mypy_boto3_athena"}
  ]
}
```

Screenshots:

Screenshot 2021-11-12 at 8 23 58 PM

Fixes part of: https://github.com/MLH-Fellowship/pyre-check/issues/58
Signed-off-by: Abishek V Ashok <abishekvashok@gmail.com>

### CODE REVIEW

**Comment by r0rshark** [comment]
@abishekvashok  @0xedward  Why is there the mypy_ prefix (e.g. mypy_boto3_apprunner)? Checking the documentation examples I just see it being imported as a boto3 client (example Athena [here](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/athena.html)). Do we need it because the library is not typed?

Did we considered reviewing AWS labda to understand if it possible to execute remote commands?

**Comment by abishekvashok** [comment]
> Did we considered reviewing AWS labda to understand if it possible to execute remote commands?

I am going through the clients one by one. I think I have wrote models for it, just wanted to spread things in various PRs for the sake of reviewing.

**Comment by abishekvashok** [comment]
> Why is there the mypy_prefix (e.g. mypy_boto3_apprunner)?

The stubs (even when mypy_boto3 is used) defines `boto3.client(client_name: str)` to return `typing.Any`. Hence, it's impossible to model without explicit type annotations.

**Comment by 0xedward** [comment]
> Why is there the mypy_ prefix (e.g. mypy_boto3_apprunner)? Checking the documentation examples I just see it being imported as a boto3 client (example Athena here). Do we need it because the library is not typed?

> The stubs (even when mypy_boto3 is used) and the code defines boto3.client(client_name: str) to return typing.Any. Hence, it's impossible to model without explicit type annotations.

@r0rshark - to add onto what @abishekvashok mentioned above: The boto3 library is too dynamic for Pysa (e.g. [clients are created at runtime](https://github.com/boto/botocore/blob/develop/botocore/client.py#L75-L105)), so we have to use type stubs. We are using [boto3-stubs](https://pypi.org/project/boto3-stubs/), which has the `mypy_boto3` prefix before all type stubs

**Comment by abishekvashok** [comment]
Fixed conflicts

**Pull request closed without merging**
