### PR TITLE
Keep GitHub Actions up to date with GitHub's Dependabot

### PR DESCRIPTION
**Pull request by cclauss**
Automates the process of creating PRs like:
* #829

Fixes software supply chain safety warnings like at the bottom right of
https://github.com/facebook/pyre-check/actions/runs/8517401397

[Keeping your actions up to date with Dependabot](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot)

[Configuration options for the dependabot.yml file - package-ecosystem](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem)

**Pre-submission checklist**
- [ ] I've ran the linters locally and fixed lint errors related to the files I modified in this PR. You can install the linters by running `pip install -r requirements-dev.txt && pre-commit install`
- [ ] `pre-commit run`

### CODE REVIEW

**Comment by kinto0** [comment]
Hi! We prefer our internal tools for this instead of github. If we change our stance on this, I'll reopen this PR.

**Comment by cclauss** [comment]
The first URL above demonstrates that the current tools are not working.

**Comment by cclauss** [comment]
@arthaud Your review, please.

**Comment by arthaud** [comment]
We aren't able te reopen because "The patch-1 branch has been deleted". Could you recreate the branch or open another PR? Thanks.

**Comment by cclauss** [comment]
Branch restored.

**Comment by cclauss** [comment]
I have restored the deleted branch but I do not have the access rights to reopen the closed pull request.

**Comment by cclauss** [comment]
For test failures on Python < 3.10 see:
* #832

**Comment by cclauss** [comment]
@arthaud Thanks much for all your help today.
* https://github.com/facebook/pyre-check/pulls?q=is%3Apr+author%3Acclauss

**Comment by cclauss** [comment]
Generated:
* #834

**Pull request closed without merging**
